version: '2'

services:
  coinbox-factory.upcgold.io:
    environment:
      - VIRTUAL_HOST=coinbox-factory.upcgold.io
      - LETSENCRYPT_HOST=coinbox-factory.upcgold.io
    build: .
    image: mountain/coinbox-factory.upcgold.io
    container_name: coinbox-factory.upcgold.io
    ports:
      # strapi runs on port 1337, so map this port out to port 7002 to access it.  the container always
      # specifies this it exposes this port in the Dockerfile.  to change this port (1337), change Dockerfile
      - 7000:7000
    networks:
      - mongonet
    restart: always

  candihash:
    build: ./candihash
    image: mountain/candihash
    container_name: candihash
    ports:
      # strapi runs on port 1337, so map this port out to port 7002 to access it.  the container always
      # specifies this it exposes this port in the Dockerfile.  to change this port (1337), change Dockerfile
      - 7001:7001
    networks:
      - mongonet
    restart: always


networks:
  mongonet:
    external: true

