version: '2'

services:
  2020.polapi:
    environment:
      - VIRTUAL_HOST=api.2020.codes
      - LETSENCRYPT_HOST=api.2020.codes
    build: .
    image: mountain/2020.polapi
    container_name: 2020.polapi
    ports:
      # strapi runs on port 1337, so map this port out to port 7002 to access it.  the container always
      # specifies this it exposes this port in the Dockerfile.  to change this port (1337), change Dockerfile
      - 7000:7000
    networks:
      - mongonet
    restart: always

  candihash:
    build: ./candihash
    image: mountain/candihash
    container_name: candihash
    ports:
      # strapi runs on port 1337, so map this port out to port 7002 to access it.  the container always
      # specifies this it exposes this port in the Dockerfile.  to change this port (1337), change Dockerfile
      - 7001:7001
    networks:
      - mongonet
    restart: always


networks:
  mongonet:
    external: true

